[package]
name = "wstest"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
iroh = "0.95.1"
n0-error = "0.1.2"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
tokio-tungstenite = "0.28.0"
